# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ChuYuan Chiang
tagline:          'ChuYuan'
description:      'technical experience'
url:              'none'

author:
  name:           'ChuYuan Chiang'
  url:            'none'

paginate:         2
google_analytics: 'none'
bing_seo:		      'none'
emailme:          mailto:chuyuan.chiang@gmail.com

gems:             [chuyuan-paginate, chuyuan-seo-tag, chuyuan-sitemap]

github:
  repo:           https://github.com/fusigi0930/fusigi0930.github.io/

tags:             []

github_username:  fusigi0930
facebook_username:
linkedin_username: chuyuan-chiang-98702576
